[TASK] Deprecate `DeclarationBlock::expandShorthands`
MyIntervals/PHP-CSS-Parser pull request #568
Opened 2024-06-18 16:15 UTC by ziegenberg

The expandShorthands/createShorthands Functions are deprecated and will be removed without substitution in version 10.0. Expanding and creating the shorthand notation is out of the scope of this library. If you want to include this functionality in your project or build it into a separate package, get the code from the v8.5.1 version of this library.

Helps with fixing #512

2024-06-18 22:56 UTC, ziegenberg commented
Rebased it.

2024-06-19 05:58 UTC, oliverklee approved these changes

2024-06-19 07:15 UTC, sabberworm commented
Is the `@deprecated` annotation already present on this method or why is there only a changelog entry without corresponding code change here?

2024-06-19 07:50 UTC, oliverklee requested changes
Indeed, this PR now looks strange.

2024-06-19 08:31 UTC, ziegenberg commented
I guess, something went missing while rebasing. I will have a look.

2024-06-19 09:12 UTC, closed without merging

2024-06-19 09:13 UTC, ziegenberg commented
Looks like this was a duplicate of #558. After rebasing, resolving the merge conflicts and pushing the PR closed on itself.

2024-06-19 09:16 UTC, oliverklee commented
It's magic! :wink: :magic_wand: