[FEATURE] Support arithmetic operators in CSS functions
MyIntervals/PHP-CSS-Parser pull request #607
Opened 2024-06-21 18:22 UTC by JakeQZ

This is the enhancement from #390.

2024-06-21 19:48 UTC, oliverklee requested changes
Looks good all in all. Only one nitpick.

2024-06-21 19:48 UTC, oliverklee commented on tests/Value/ValueTest.php
> +
Let's make this file strict.

2024-06-21 21:21 UTC, JakeQZ commented on tests/Value/ValueTest.php
> +
Done.

2024-06-21 21:26 UTC, oliverklee approved these changes
LGTM. Thanks for picking this up! ❤️

2024-06-21 21:27 UTC, oliverklee requested changes
Ah, no, stop the press: We still need a changelog entry for this new feature.

2024-06-21 21:46 UTC, JakeQZ commented
I've added strict types declaration to the new (test) source file.

@sabberworm, can you give this a quick look to confirm you think it's OK for now.

Longer term, I think it would be cleaner to introduce a `Value\Expression` class to encapsulate arithmetic.  For now, this change allows construction from parsing of a `RuleValueList` with components like `{0: Size, 1: string, 2: Size}` where the string is the operator.  Longer term we'd want to support nested expressions with brackets, and direct expressions as values (both of which I think CSS4 allows, the latter with syntax like `width: (100px + 10%)`, i.e. omission of the `calc` keyword, though can't offhand find a reference).

2024-06-21 21:55 UTC, JakeQZ commented
> Ah, no, stop the press: We still need a changelog entry for this new feature.

Indeed we do.  It's lack was a deliberate alertness test ;)

Also corrected nomenclature of the numberic part of a length value (MDN calls it a 'number' not a 'value').

2024-06-21 23:48 UTC, JakeQZ commented
I've updated this again.  I noted that arithmetic in `calc` already worked, so the test I had for `calc(A + B + C)` was already passing.  So I've extended that test to also include `max(X, A + B + C)`.

2024-06-22 02:16 UTC, JakeQZ commented
> Longer term, I think it would be cleaner to introduce a `Value\Expression` class to encapsulate arithmetic

Just re-spotted that #389 seeks to do just that.  Though it is a PR on top of a PR, so may be somewhat awkward to unravel.

2024-06-22 09:31 UTC, oliverklee commented
> Longer term, I think it would be cleaner to introduce a `Value\Expression` class to encapsulate arithmetic. 

Yes, absolutely. I'd also like to check our class naming and structure against the terms and concepts used in the the [official specification](https://www.w3.org/TR/css-syntax-3/).

2024-06-23 00:03 UTC, JakeQZ commented
> I'd also like to check our class naming and structure against the terms and concepts used in the the [official specification](https://www.w3.org/TR/css-syntax-3/).

I'm finding a close if not exact match there.  Kudos to @sabberworm.  But, yes, please do review.

2024-06-23 00:08 UTC, JakeQZ commented
> Just re-spotted that #389 seeks to do just that. Though it is a PR on top of a PR, so may be somewhat awkward to unravel.

Looking at that, the new `Expression` class doesn't seem to be connected to anything, so it seems a WIP.  Although I had briefly looked at it before, I had forgotten.  So I would consider it two people independently coming up with the same idea...

2024-06-23 07:02 UTC, oliverklee approved these changes
Neat!

2024-06-23 07:02 UTC, oliverklee commented
> Yes, absolutely. I'd also like to check our class naming and structure against the terms and concepts used in the the [official specification](https://www.w3.org/TR/css-syntax-3/).

… but not as part of this PR. :-)

2024-06-23 07:03 UTC, merged