[CLEANUP] Always escape backslashes in strings
MyIntervals/PHP-CSS-Parser pull request #639
Opened 2024-07-02 08:12 UTC by oliverklee

This was done using the `string_implicit_backslashes` PHP-CS-Fixer rule.

2024-07-02 21:56 UTC, JakeQZ requested changes
In some of the regex patterns with the `PCRE_EXTENDED` modifier, the comments have become misaligned.

2024-07-02 21:56 UTC, JakeQZ commented on src/Property/KeyframeSelector.php
> +    (\\d+%)                                                          # keyframe animation progress percentage (e.g. 50%)
I think the comment here neeeds moving to align with the others.

2024-07-02 21:56 UTC, JakeQZ commented on src/Property/Selector.php
> +        (\\:(                        # pseudo classes
Same here.

2024-07-02 21:56 UTC, JakeQZ commented on src/Property/Selector.php
> +        \\:{1,2}(                # pseudo-elements
And here.

2024-07-03 07:09 UTC, oliverklee commented
Fixed the alignments and repushed.

2024-07-03 16:39 UTC, JakeQZ approved these changes
Looks fine now.

2024-07-03 16:39 UTC, merged