[TASK] Update the code of conduct to version 2.1
MyIntervals/PHP-CSS-Parser pull request #652
Opened 2024-07-28 15:58 UTC by oliverklee

Copy version 2.1 of the contributor convenant code of conduct without any changes except those:

- use our contact email address
- drop links additional resources related to the contributor covenant CoC

https://www.contributor-covenant.org/version/2/1/code_of_conduct/

2024-07-28 22:58 UTC, JakeQZ requested changes
All seems fine, apart from invalid markdown and broken links in the attribution section.

2024-07-28 22:58 UTC, JakeQZ commented on CODE_OF_CONDUCT.md
> +[https://www.contributor-covenant.org/version/2/1/code_of_conduct.html][v2.1].
The link doesn't work.  I think we need to lose the square brackets, and the version number at the end (the version is already in the URL).
```suggestion
https://www.contributor-covenant.org/version/2/1/code_of_conduct.html.
```

2024-07-28 22:58 UTC, JakeQZ commented on CODE_OF_CONDUCT.md
>  This Code of Conduct is adapted from the [Contributor Covenant][homepage],
I think this invalid markdown should be fixed as part of this change.
```suggestion
This Code of Conduct is adapted from the [Contributor Covenant](https://www.contributor-covenant.org/),
```

2024-07-29 21:37 UTC, jjriv approved these changes

2024-07-29 22:31 UTC, JakeQZ approved these changes
Looks fine now.

2024-07-29 22:32 UTC, merged