[TASK] Avoid Hungarian notation in a testcase
MyIntervals/PHP-CSS-Parser pull request #700
Opened 2024-09-01 15:02 UTC by oliverklee

2024-09-02 23:40 UTC, JakeQZ requested changes
Good to introduce some new variables for the arrays that were temporarily assigned to a variable for storing a value from that array.

A couple of new names don't seem right or completely clear, and one rename has been missed.

2024-09-02 23:40 UTC, JakeQZ commented on tests/ParserTest.php
> +        $expectedLineNumbers = [7, 26]; // expected line numbers
We can lose the now-redundant comment.

2024-09-02 23:40 UTC, JakeQZ commented on tests/ParserTest.php
> +        $actualUrls = [];
This should be renamed `$actualLineNumbers`.

2024-09-02 23:40 UTC, JakeQZ commented on tests/ParserTest.php
> +        $expectedColorLines = [28, 29, 30];
I'd prefer `$expectedColorLineNumbers`.

2024-09-02 23:40 UTC, JakeQZ commented on tests/ParserTest.php
>          $aActualColorLines = [];
This Hungarian variable has been missed.

2024-09-03 10:59 UTC, oliverklee commented
Updated and repushed.

2024-09-03 16:03 UTC, JakeQZ approved these changes

2024-09-03 16:03 UTC, merged