[CLEANUP] Autoformat the code
MyIntervals/PHP-CSS-Parser pull request #748
Opened 2024-10-26 08:05 UTC by oliverklee

2024-10-30 22:50 UTC, JakeQZ requested changes
Just one alignment issue; otherwise fine.

2024-10-30 22:56 UTC, oliverklee commented
> Just one alignment issue

Which one?

2024-10-30 22:59 UTC, JakeQZ requested changes
Sorry, failed to submit the comment.

2024-10-30 22:59 UTC, JakeQZ commented on tests/CSSList/AtRuleBlockListTest.php
> +            ',
The closing quote should be indented to align with the opening quote.
```suggestion
                ',
```

2024-10-31 14:08 UTC, JakeQZ approved these changes

2024-10-31 14:09 UTC, merged